### ISSUE TITLE
do I need to add age into the model?

### ISSUE THREAD

**Issue by ChuanJ** [myles-lewis/glmmSeq#36]
Hi,
Thanks for developing this useful package. I am wondering about the age correction. Do I need to add it to the model? Or other confounders?

Best,

**Comment by myles-lewis** [comment]
You can add covariates easily, by simply adding these variables into the model, e.g. batch. The covariates can either be categorical e.g. batch/gender, or numerical e.g. age. But I generally don't include age or gender unless there is a good reason to include these. Including covariates essentially adjusts out the effects of these parameters so that they don't confound your model. So it's good to include batch (+/- technical parameters) which affect your reads.

**Comment by ChuanJ** [comment]
I see. I have the same feelings after I tried it!!! Thank you !

Le sam. 20 juil. 2024 à 18:11, Myles Lewis ***@***.***> a
écrit :
